# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dexie.js - Minimalistic IndexedDB Wrapper
email: david.fahlander@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dexie.js documentation.
url: "https://dexie.org" # the base hostname & protocol for your site
twitter_username: dfahlander
github_username:  dfahlander
include: ['docs/','cloud/','contact.md','.well-known']
exclude: ['*.sh']
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
encoding: UTF-8
gfm_quirks: paragraph_end

# Build settings
markdown: kramdown
permalink: short-urls-jekyll
